services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: hsm
      POSTGRES_PASSWORD: hsm_dev_password
      POSTGRES_DB: hsm_france
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
